// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJIULjSbxj-GX3aII1iMd1_b4295YuJa0',
    appId: '1:777089147131:web:f9402a445178d98c6a505e',
    messagingSenderId: '777089147131',
    projectId: 'mathnav-69d41',
    authDomain: 'mathnav-69d41.firebaseapp.com',
    storageBucket: 'mathnav-69d41.firebasestorage.app',
    measurementId: 'G-P0SMJXEJLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqh5lPPnd7JozJnVRAmPdYQPB-o30lWSc',
    appId: '1:777089147131:android:2f00082ff8f36fa46a505e',
    messagingSenderId: '777089147131',
    projectId: 'mathnav-69d41',
    storageBucket: 'mathnav-69d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZk83axr29LtkasNiUtmYOFvdIYeX0M8',
    appId: '1:777089147131:ios:97329d3366678b0d6a505e',
    messagingSenderId: '777089147131',
    projectId: 'mathnav-69d41',
    storageBucket: 'mathnav-69d41.firebasestorage.app',
    iosBundleId: 'com.example.mathnav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUZk83axr29LtkasNiUtmYOFvdIYeX0M8',
    appId: '1:777089147131:ios:97329d3366678b0d6a505e',
    messagingSenderId: '777089147131',
    projectId: 'mathnav-69d41',
    storageBucket: 'mathnav-69d41.firebasestorage.app',
    iosBundleId: 'com.example.mathnav',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJIULjSbxj-GX3aII1iMd1_b4295YuJa0',
    appId: '1:777089147131:web:a947bb0d35815cd06a505e',
    messagingSenderId: '777089147131',
    projectId: 'mathnav-69d41',
    authDomain: 'mathnav-69d41.firebaseapp.com',
    storageBucket: 'mathnav-69d41.firebasestorage.app',
    measurementId: 'G-9EQQKLK9MH',
  );
}
